In [41]:
library(tidyverse)
library(oce)

In [73]:
ctd_ds <- read.csv("BCO-DMO/ctd.csv", na.strings="nd")

In [74]:
str(ctd_ds)

'data.frame':	288045 obs. of  21 variables:
 $ cruise_no : int  1 1 1 1 1 1 1 1 1 1 ...
 $ Cruise_ID1: chr  "93HG_001" "93HG_001" "93HG_001" "93HG_001" ...
 $ Cruise_ID2: chr  "CAR-001" "CAR-001" "CAR-001" "CAR-001" ...
 $ Year      : int  1995 1995 1995 1995 1995 1995 1995 1995 1995 1995 ...
 $ Month     : int  11 11 11 11 11 11 11 11 11 11 ...
 $ Day       : int  8 8 8 8 8 8 8 8 8 8 ...
 $ Date      : chr  "1995-11-08" "1995-11-08" "1995-11-08" "1995-11-08" ...
 $ Latitude  : num  10.5 10.5 10.5 10.5 10.5 10.5 10.5 10.5 10.5 10.5 ...
 $ Longitude : num  -64.7 -64.7 -64.7 -64.7 -64.7 ...
 $ press     : num  1.01 2.01 4.02 6.03 8.05 ...
 $ depth     : num  1 2 4 6 8 10 12 14 16 18 ...
 $ temp      : num  NA 27.5 27.5 27.5 27.5 ...
 $ sal       : num  36.6 36.6 36.6 36.6 36.6 ...
 $ potemp    : num  NA 27.5 27.5 27.5 27.5 ...
 $ sigma_t   : num  NA 23.8 23.8 23.8 23.8 ...
 $ sigma_0   : num  NA 23.8 23.8 23.8 23.8 ...
 $ O2_ml_L   : num  NA 3.96 3.98 3.98 3.99 ...
 $ beam_cp   : num  NA NA NA NA NA NA NA NA NA NA ...
 $ beam_att  : num  NA NA NA NA NA NA NA NA NA NA ...
 $ fluor_CTD : num  0.173 0.176 0.166 0.164 0.17 0.175 0.164 0.159 0.16 0.167 ...
 $ fluor_chla: num  NA NA NA NA NA NA NA NA NA NA ...

In [75]:
ctd_ds$date <- paste(ctd_ds$Year,'-',ctd_ds$Month,'-',ctd_ds$Day, sep='')
ctd_ds$date <- as.Date(ctd_ds$date, format="%Y-%m-%d")

In [76]:
unique(ctd_ds$date)

  [1] "1995-11-08" "1995-12-14" "1996-01-13" "1996-02-14" "1996-03-13"
  [6] "1996-04-16" "1996-05-09" "1996-06-12" "1996-07-10" "1996-08-06"
 [11] "1996-09-11" "1996-10-08" "1996-11-10" "1996-12-09" "1997-01-07"
 [16] "1997-02-13" "1997-03-12" "1997-04-15" "1997-05-10" "1997-06-17"
 [21] "1997-07-08" "1997-08-17" "1997-09-17" "1997-10-14" "1997-11-13"
 [26] "1997-12-17" "1998-01-14" "1998-02-11" "1998-03-12" "1998-04-21"
 [31] "1998-06-09" "1998-07-09" "1998-08-05" "1998-09-01" "1998-10-14"
 [36] "1998-11-10" "1998-12-16" "1999-01-12" "1999-02-10" "1999-03-04"
 [41] "1999-04-07" "1999-05-06" "1999-06-08" "1999-07-15" "1999-08-11"
 [46] "1999-09-14" "1999-10-05" "1999-11-04" "1999-12-07" "2000-01-11"
 [51] "2000-02-08" "2000-03-09" "2000-04-10" "2000-05-11" "2000-06-06"
 [56] "2000-07-07" "2000-08-09" "2000-09-12" "2000-10-10" "2000-11-03"
 [61] "2000-12-05" "2001-01-11" "2001-02-16" "2001-03-14" "2001-04-04"
 [66] "2001-05-05" "2001-06-10" "2001-07-10" "2001-08-07" "2001-09-11"
 [71] "2001-10-09" "2001-11-06" "2001-12-11" "2002-01-10" "2002-02-14"
 [76] "2002-03-12" "2002-04-02" "2002-05-07" "2002-06-12" "2002-07-09"
 [81] "2002-08-06" "2002-10-03" "2002-11-07" "2002-12-05" "2003-01-14"
 [86] "2003-02-11" "2003-03-11" "2003-04-08" "2003-05-13" "2003-06-10"
 [91] "2003-07-08" "2003-08-05" "2003-09-10" "2003-11-11" "2003-12-09"
 [96] "2004-01-13" "2004-02-10" "2004-03-09" "2004-04-06" "2004-05-13"
[101] "2004-06-08" "2004-07-07" "2004-08-10" "2004-09-07" "2004-10-05"
[106] "2004-11-09" "2004-12-07" "2005-01-11" "2005-02-09" "2005-03-09"
[111] "2005-04-05" "2005-05-10" "2005-06-14" "2005-07-12" "2005-08-09"
[116] "2005-10-04" "2005-12-14" "2006-01-12" "2006-02-07" "2006-03-16"
[121] "2006-04-04" "2006-05-10" "2006-06-06" "2006-07-04" "2006-08-03"
[126] "2006-09-12" "2006-10-10" "2006-11-02" "2006-12-05" "2007-02-06"
[131] "2007-03-06" "2007-04-10" "2007-05-08" "2007-06-05" "2007-07-03"
[136] "2007-08-07" "2007-09-04" "2007-10-09" "2007-11-30" "2007-12-11"
[141] "2008-01-10" "2008-02-12" "2008-03-11" "2008-04-08" "2008-05-06"
[146] "2008-06-04" "2008-07-08" "2008-08-05" "2008-09-10" "2008-10-10"
[151] "2008-11-11" "2008-12-10" "2009-01-13" "2009-02-10" "2009-03-03"
[156] "2009-04-07" "2009-05-08" "2009-06-02" "2009-07-14" "2009-08-11"
[161] "2009-09-15" "2009-10-06" "2009-11-10" "2009-12-08" "2010-01-07"
[166] "2010-02-09" "2010-03-09" "2010-04-07" "2010-05-11" "2010-06-08"
[171] "2010-08-04" "2010-09-15" "2010-10-04" "2010-11-09" "2010-12-08"
[176] "2011-01-11" "2011-02-08" "2011-03-15" "2011-04-12" "2011-05-10"
[181] "2011-06-09" "2011-07-07" "2011-08-09" "2011-09-06" "2011-10-04"
[186] "2012-11-18" "2012-01-10" "2012-02-07" "2012-03-16" "2012-04-10"
[191] "2012-05-15" "2012-07-26" "2012-08-14" "2012-09-10" "2012-10-10"
[196] "2012-11-08" "2012-12-03" "2013-03-05" "2013-04-09" "2013-05-09"
[201] "2013-06-11" "2013-07-11" "2013-08-13" "2013-09-11" "2013-10-08"
[206] "2013-11-13" "2013-12-04" "2014-01-14" "2014-02-04" "2014-04-01"
[211] "2014-05-06" "2014-06-13" "2014-09-03" "2014-10-07" "2014-11-12"
[216] "2014-12-09" "2015-02-14" "2015-03-10" "2015-04-14" "2015-07-29"
[221] "2015-08-18" "2015-09-10" "2015-11-16" "2015-12-09" "2016-01-13"
[226] "2016-02-04" "2016-05-11" "2016-06-07" "2016-12-21" "2017-01-17"

In [45]:
# import interpolation functions
source('interpolateData.r')

In [46]:
ctd_temp_int = interpolateDF(prepdataframe(ctd_ds, "temp"))

In [47]:
iso21_depth <- ctd_temp_int %>%
    group_by(date) %>%
    filter(depth > 6) %>%
    mutate(iso21 = value_int < 21) %>% # create new column that gives "True" for values at MLD
    filter(iso21 == T) %>% # only take "True" values 
    slice(1) # takes the first occurrence

In [48]:
iso21_df <- iso21_depth %>%
    rename(Isotherm_21 = depth) %>%
    select(date, Isotherm_21)

In [49]:
# MLD from sigma_t

In [50]:
ctd_sigma_t_int = interpolateDF(prepdataframe(ctd_ds, "sigma_t"))

In [51]:
ctd_sigma_t_diff <- ctd_sigma_t_int %>%
    group_by(date) %>%
    do(data.frame( sigma_t = .$value_int, sigma_t_diff = c(NA,diff(.$value_int)), depth = .$depth))

head(ctd_sigma_t_diff)

  date       sigma_t  sigma_t_diff depth
1 1995-11-08 23.76400          NA  0
2 1995-11-08 23.76400 0.000000000  1
3 1995-11-08 23.76400 0.000000000  2
4 1995-11-08 23.76950 0.005500000  3
5 1995-11-08 23.77500 0.005500000  4
6 1995-11-08 23.77895 0.003947205  5

In [52]:
# Criterion 1
mld_depth <- ctd_sigma_t_diff %>%
    group_by(date) %>%
    filter(depth > 9) %>%
    mutate(mld = sigma_t_diff >= 0.125 | sigma_t_diff <= -0.125) %>% # create new column that gives "True" for values at MLD
    filter(mld == T) %>% # only take "True" values 
    slice(1) # takes the first occurrence

In [53]:
#Criterion 2 -- better apparently (i think from some paper or email!)
mld_depth_2 <- ctd_sigma_t_diff %>%
    group_by(date) %>%
    filter(depth > 9) %>%
    mutate(mld = sigma_t >= sigma_t[1]+0.2 | sigma_t <= sigma_t[1]-0.2) %>% # create new column that gives "True" for values at MLD
    filter(mld == T) %>% # only take "True" values 
    slice(1) # takes the first occurrence

In [54]:
mld_df <- mld_depth_2 %>%
    rename(MLD = depth) %>%
    select(date, MLD)

In [55]:
# Calculate SST from Temperature at surface
sst_10m <- ctd_temp_int %>%
  group_by(date) %>%
  filter(depth <= 10) %>%
  summarize(sst = mean(value_int))

In [56]:
# Combine Isotherm and MLD data frames
CTD_combined_data <- list(iso21_df, mld_df, sst_10m) %>% 
  reduce(left_join, by = "date") %>% as.data.frame()

#write.csv(CTD_combined_data, "../DATA/January/CTD_Isotherm21_MLD.csv")

In [57]:
write.csv(CTD_combined_data, "processed/CTD_Isotherm21_MLD.csv")

In [58]:
saveRDS(CTD_combined_data, "processed/CTD_Isotherm21_MLD.rds")

# calculate upwelling index

In [39]:
UpwellingIndex <- ctd_temp_int %>%
    group_by(date) %>%
    filter(depth == 50) %>%
    mutate(ui = case_when(
                         value_int<=20.0 ~ "strong",
                         value_int<=21.0 ~ "moderate",
                         value_int<=22.0 ~ "weak",
                         value_int>22.0 ~ "relaxed"),
          upwelling = case_when(
                         value_int<=22.0 ~ "upwelling",
                         value_int>22.0 ~ "relaxed"),
          ) %>% select(date, ui, upwelling)

head(UpwellingIndex)

  date       ui       upwelling
1 1995-11-08 relaxed  relaxed
2 1995-12-14 relaxed  relaxed
3 1996-01-13 relaxed  relaxed
4 1996-02-14 relaxed  relaxed
5 1996-03-13 moderate upwelling
6 1996-04-16 moderate upwelling

In [40]:
saveRDS(UpwellingIndex, "processed/CTD_UpwellingIndex.rds")